"""Interactive init wizard: guides first-time users through AIRD setup."""

import os
import sys
from pathlib import Path

# Platform choices shown to the user: (label, scheme, example connection string)
PLATFORMS = [
    ("DuckDB", "duckdb", "duckdb:///path/to/your/database.duckdb"),
    ("SQLite", "sqlite", "sqlite:///path/to/your/database.db"),
    ("Snowflake", "snowflake", "snowflake://user:pass@account/database/schema?warehouse=WH"),
]

# Workload choices: (label, config value, description)
WORKLOADS = [
    ("Analytics (L1)", "analytics", "dashboards, BI, basic reporting"),
    ("RAG (L2)", "rag", "retrieval-augmented generation, search"),
    ("Training (L3)", "training", "model training, fine-tuning"),
]

CONFIG_DIR = Path.home() / ".aird"
CONFIG_PATH = CONFIG_DIR / "config.yaml"


def _prompt(message: str) -> str:
    """Prompt and return stripped input. Raises EOFError on empty stdin."""
    try:
        return input(message).strip()
    except EOFError:
        return ""


def _prompt_choice(options: list[tuple], prompt_msg: str = "  > ") -> int:
    """Show numbered options and return 0-based index of the user's choice."""
    while True:
        raw = _prompt(prompt_msg)
        if not raw:
            continue
        try:
            idx = int(raw)
        except ValueError:
            print(f"  Please enter a number between 1 and {len(options)}.")
            continue
        if 1 <= idx <= len(options):
            return idx - 1
        print(f"  Please enter a number between 1 and {len(options)}.")


def _step_platform() -> tuple[str, str, str]:
    """Step 1: Choose platform. Returns (label, scheme, example)."""
    print("\nStep 1: Choose your platform")
    for i, (label, _scheme, _example) in enumerate(PLATFORMS, 1):
        print(f"  [{i}] {label}")
    idx = _prompt_choice(PLATFORMS)
    return PLATFORMS[idx]


def _step_connection(scheme: str, example: str) -> str:
    """Step 2: Get connection string from user."""
    print(f"\nStep 2: Connection string")
    print(f"  {scheme.title()} format: {example}")
    while True:
        conn = _prompt("  > ")
        if conn:
            return conn
        print("  Connection string cannot be empty.")


def _step_test_connection(connection_string: str) -> dict:
    """Step 3: Test the connection and return discovery inventory. Retries on failure."""
    print("\nStep 3: Testing connection...")
    while True:
        try:
            from agent.discovery import discover
            inv = discover(connection_string)
            table_count = len(inv.get("tables", []))
            schema_count = len(inv.get("schemas", []))
            print(f"  \u2713 Connected successfully! Found {table_count} tables in {schema_count} schemas.")
            return inv
        except Exception as e:
            print(f"  \u2717 Connection failed: {e}")
            choice = _prompt("  Retry with a different connection string? [Y/n] ")
            if choice.lower() in ("n", "no"):
                raise SystemExit(1)
            connection_string_new = _prompt("  > ")
            if connection_string_new:
                connection_string = connection_string_new


def _step_workload() -> str:
    """Step 4: Choose target workload. Returns config value (analytics/rag/training)."""
    print("\nStep 4: Target workload (what will you use this data for?)")
    for i, (label, _value, desc) in enumerate(WORKLOADS, 1):
        print(f"  [{i}] {label} \u2014 {desc}")
    idx = _prompt_choice(WORKLOADS)
    return WORKLOADS[idx][1]


def _step_save(connection_string: str, workload: str) -> None:
    """Step 5: Optionally save config to ~/.aird/config.yaml."""
    print(f"\nStep 5: Save configuration?")
    choice = _prompt(f"  Save to {CONFIG_PATH}? [Y/n] ")
    if choice.lower() in ("n", "no"):
        print("  Skipped saving.")
        return
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    content = (
        f"# Generated by aird init\n"
        f'connection: "{connection_string}"\n'
        f"target_workload: {workload}\n"
    )
    CONFIG_PATH.write_text(content)
    print(f"  \u2713 Saved to {CONFIG_PATH}")


def run_init() -> None:
    """Main entry point for the init wizard."""
    # Non-interactive detection
    if not sys.stdin.isatty():
        print("Error: aird init requires an interactive terminal.", file=sys.stderr)
        sys.exit(1)

    try:
        print("Welcome to AIRD \u2014 AI-Ready Data Assessment")
        print("\u2550" * 43)

        label, scheme, example = _step_platform()
        connection_string = _step_connection(scheme, example)
        _step_test_connection(connection_string)
        workload = _step_workload()
        _step_save(connection_string, workload)

        print(f'\nYou\'re all set! Run: aird assess -c "{connection_string}"')

    except KeyboardInterrupt:
        print("\nCancelled.")
        sys.exit(0)

